#include <wx/wx.h> //GUI library
#include "RtAudio.h" //Audio library header file
#include <thread> //This lets you create a new thread to run the audio independent of the GUI
#include <atomic>  //Allows you to create atomic variables. Atomic variables are special variables that can be read and written to by multiple threads without causing race conditions.
#include "VoiceFunctions.h" //This header file contains the synth voice class. It will contain the oscillator, envelope, and filter methods that will be used throughout the code.
#include "KeyInputManager.h" //Manages keyboard input
#include "stdc++.h"//
#include <stdio.h>
#include <vector>
#include <algorithm>
#include <cmath>
#include <string>
#include <random>
#include "Modulators.h"
#include "fxRack.h"
#include <wx/dcbuffer.h> //Add this include for wxAutoBufferedPaintDC
#include "Goodverb.h"
#include "GUI.h"



//****************************************************************************************************************************************************************
//IMPORTANT PART FOR GUI IMPLEMENTATION
//Note: Atomic variables are special variables designed for multithreading. They're designed to prevent race conditions, usually caused by multiple threads/cores
//accessing the same variable at once. Any variables that can be accessed by both the GUI and the audio code should be declared as atomics.
//
//Note #2: It may be necessary to implement something called cache padding so each variable is stored on a separate cache. This is recommended for optimization,
//but I left it out for the sake of simplicity and readability. I may change my mind on this later.
//****************************************************************************************************************************************************************

//GENERAL SYNTH PARAMETERS
//These parameters require reinitialization of the audio device to be changed.
std::atomic<int> sampRate = 44100;//DON'T ADD A UI ELEMENT FOR THIS YET
std::atomic<int> bufferSize = 32;//DON'T ADD A UI ELEMENT FOR THIS YET
std::atomic<bool> reInit = false; //This should trigger the audioStart() method and reinitialize the device. DON'T ADD A UI ELEMENT FOR THIS YET

int voiceCount = 16;//This should be changeable via dropdown menu (NOT YET IMPLEMENTED)
int channelCount = 2;//Not changeable.


voice* voices = new voice[voiceCount];  //Dynamically allocate an array of voice objects.
LFO* LFOs = new LFO[2];
KeyInputManager* keyInputManager = new KeyInputManager(); //Creates keyinput manager object.
Delay* dly = new Delay();
Distortion* distortion = new Distortion();
Flanger* flanger = new Flanger();
Chorus* chorus = new Chorus();
Goodverb* goodverb = new Goodverb();



//Creating global variables for the voice objects
float filtCutoff = 220;
float oscVol = 0.1;
bool oscToggle = true;
int oscWave = 1;
double oscPhsOff = 0;
double oscPtchShft = 0;

bool osc2Toggle = true;
int osc2Wave = 1;
double osc2Vol = 0.01;
double osc2PhsOff = 0;
double osc2PtchShft = 0.1;

double atk = 0.1;
double dcy = 1;
double sus = 0.5;
double rls = 0.5;

double filtQ = 1;
double filtType = 1;
bool keyTrck = false;


//This loop is called by the audio device once per buffer. It generates audio data in batches and writes it to the buffer.
int audioLoop(void* outputBuffer, void* inputBuffer, unsigned int nBufferFrames,
    double streamTime, RtAudioStreamStatus status, void* userData)
{
    double* buffer = (double*)outputBuffer;
    double* lastValues = (double*)userData;

    if (status)
        wxLogMessage("System Underflow Detected");
    for (int i = 0; i < nBufferFrames; i++) {
        for (int j = 0; j < channelCount; j++) {
            buffer[i * channelCount + j] = 0;
        }
    }

    for (int i = 0; i < 2; i++) {
        LFOs[i].lfoGen();
    }

    for (int i = 0; i < voiceCount; i++) {

        voices[i].setVars();

        voices[i].oscillator(nBufferFrames, channelCount); //This is where the oscillator method is called.
        voices[i].oscillator2(nBufferFrames, channelCount);
        //The buffer is filled with the audio data generated by the oscillator. The phase is updated by the oscillator method and returned to the main loop.

        voices[i].biquadCoefs(sampRate); //Sets the coefficients used to calculate the filter output
        voices[i].biquadFilter();

        voices[i].envelope(nBufferFrames, channelCount, sampRate);
        for (int j = 0; j < nBufferFrames * channelCount; j++) { //adds together all the different voices' outputs
            buffer[j] += voices[i].localBuff[j];
        }

    }
    //flanger->flanger(buffer);
    //chorus->chorus(buffer);
    dly->delay(buffer);
    //goodverb->reverb(buffer);
    //distortion->distort(buffer);


    return 0;

}

class AudioManager {
public: 
    AudioManager() : running(false) {}

    void start() {//Starts the audio on a separate thread so 

        audioThread = std::thread(&AudioManager::audioStart, this);
        audioThread.detach();
    }

    void stop() {
        running = false;
        if (audioThread.joinable()) {
            audioThread.join();
        }
    }

private:
    void audioStart() { //Initializes the audio device.

        RtAudio dac;
        std::vector<unsigned int> deviceIds = dac.getDeviceIds();
        if (deviceIds.size() < 1) {
            wxLogMessage("No audio devices found!");
            return;
        }

        RtAudio::StreamParameters parameters;
        parameters.deviceId = dac.getDefaultOutputDevice(); //Set the device ID to the default output device
        parameters.nChannels = channelCount; //Set the number of channels to 2 (left and right channel for stereo)
        parameters.firstChannel = 0;
        unsigned int sampleRate = sampRate; //Standard CD quality sample rate
        unsigned int bufferFrames = bufferSize; //The number of sample frames. Make this higher for less CPU usage, or lower for less latency. This should be changable by the user in the final version. Also, it should be a power of two.
        double data[2] = { 0, 0 }; //IDK what this does but it was in the example code for the library i downloaded so I'm keeping it for now. I'll remove it if it turns out to be unnecessary.

        if (dac.openStream(&parameters, NULL, RTAUDIO_FLOAT64, sampleRate,
            &bufferFrames, &audioLoop, (void*)&data)) {
            return; //Checks for a problem with device settings
        }

        //Once the stream is opened, this starts the stream
        if (dac.startStream()) {
            return;
        }

        running = true;
        while (running) {
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }

        //Stops the audio stream
        if (dac.isStreamRunning())
            dac.stopStream();

        if (dac.isStreamOpen()) dac.closeStream();

    }

    std::thread audioThread; //Create a new thread to run the audio independent of the GUI
    std::atomic<bool> running; //DON'T ADD A UI ELEMENT FOR THIS. This value is used to stop the audio thread when the program closes. Since the stop() function is called by the App class destructor, it is declared as an atomic to avoic race conditions. DON'T ADD A UI ELEMENT FOR THIS
};



//****************************************************************************************************************************************************************
//BELOW IS THE GUI CODE
//IT CONTAINS THE ENTRY POINT OF THE PROGRAM
//THE AUDIO AND GUI MUST BE COMPUTED ON SEPARATE THREADS. OTHERWISE THE AUDIO PROCESSING LOOP WILL NOT RUN.
//****************************************************************************************************************************************************************

 //std::atomic<double> cutoffSet = 220.0;

class App : public wxApp {
public:


    bool OnInit() { //This is the entry point for the program.
        wxFrame* window = new wxFrame(NULL, wxID_ANY, "GUI Test", wxDefaultPosition, wxSize(600, 400));
        wxPanel* panel = new wxPanel(window);

        guiSetup(panel, window);

        window->Show();
        window->SetFocus();

        window->Bind(wxEVT_KEY_DOWN, &KeyInputManager::OnKeyDown, keyInputManager);
        window->Bind(wxEVT_KEY_UP, &KeyInputManager::OnKeyUp, keyInputManager);

        audioManager.start();

        // Timer updating cutoffSet and debug info regularly
        wxTimer* updateTimer = new wxTimer(window);

        updateTimer->Start(50); // Update every 50ms

        return true;
    }

    int OnExit() noexcept {
        audioManager.stop();
        return 0;
    }

private:

    AudioManager audioManager;
};

wxIMPLEMENT_APP(App); //Initializes the GUI apps