#include <wx/wx.h> //GUI library
#include "RtAudio.h" //Audio library header file
#include <thread> //This lets you create a new thread to run the audio independent of the GUI
#include <atomic>  //Allows you to create atomic variables. Atomic variables are special variables that can be read and written to by multiple threads without causing race conditions.
#include "VoiceFunctions.h" //This header file contains the synth voice class. It will contain the oscillator, envelope, and filter methods that will be used throughout the code.
#include "KeyInputManager.h" //Manages keyboard input
#include "stdc++.h"
#include <stdio.h>
#include <vector>
#include <algorithm>
#include <cmath>
#include <string>
#include <random>
#include "Modulators.h"
#include "fxRack.h"
#include <wx/dcbuffer.h> //Add this include for wxAutoBufferedPaintDC
#include "Goodverb.h"




//****************************************************************************************************************************************************************
//IMPORTANT PART FOR GUI IMPLEMENTATION
//Below this comment, I have declared an atomic global variable for each changeable synth parameter. I want you to map them to a knobs, sliders, buttons, etc.
//
//Note: Atomic variables are special variables designed for multithreading. They're designed to prevent race conditions, usually caused by multiple threads/cores
//accessing the same variable at once. Any variables that can be accessed by both the GUI and the audio code should be declared as atomics.
//
//Note #2: It may be necessary to implement something called cache padding so each variable is stored on a separate cache. This is recommended for optimization,
//but I left it out for the sake of simplicity and readability. I may change my mind on this later.
//****************************************************************************************************************************************************************

//GENERAL SYNTH PARAMETERS
//These parameters require reinitialization of the audio device to be changed.
std::atomic<int> sampRate = 44100;//This should be changeable via dropdown menu. DON'T ADD A UI ELEMENT FOR THIS YET
std::atomic<int> bufferSize = 128;//This should be changeable via dropdown menu. DON'T ADD A UI ELEMENT FOR THIS YET
std::atomic<bool> reInit = false; //Set this True if any of the above parameters are changed. This should trigger the audioStart() method and reinitialize the device. DON'T ADD A UI ELEMENT FOR THIS YET

int voiceCount = 16;//This should be changeable via dropdown menu (NOT YET IMPLEMENTED)
int channelCount = 2;//Not changeable.


voice* voices = new voice[voiceCount];  //Dynamically allocate an array of voice objects.
LFO* LFOs = new LFO[2];
KeyInputManager* keyInputManager = new KeyInputManager(); //Creates keyinput manager object.
Delay* dly = new Delay();
Distortion* distortion = new Distortion();
Flanger* flanger = new Flanger();
Chorus* chorus = new Chorus();
Goodverb* goodverb = new Goodverb();

//This loop is called by the audio device once per buffer. It generates audio data in batches and writes it to the buffer.
int audioLoop(void* outputBuffer, void* inputBuffer, unsigned int nBufferFrames,
    double streamTime, RtAudioStreamStatus status, void* userData)
{
    double* buffer = (double*)outputBuffer;
    double* lastValues = (double*)userData;

    if (status)
        wxLogMessage("System Underflow Detected");
    for (int i = 0; i < nBufferFrames; i++) {
        for (int j = 0; j < channelCount; j++) {
            buffer[i * channelCount + j] = 0;
        }
    }

    for (int i = 0; i < 2; i++) {
        LFOs[i].lfoGen();
    }

    for (int i = 0; i < voiceCount; i++) {

        //noteSetter(i); //sets the osc frequency based on the note selected

        voices[i].oscillator(nBufferFrames, channelCount); //This is where the oscillator method is called.
        voices[i].oscillator2(nBufferFrames, channelCount);
        //The buffer is filled with the audio data generated by the oscillator. The phase is updated by the oscillator method and returned to the main loop.

        voices[i].biquadCoefs(sampRate); //Sets the coefficients used to calculate the filter output
        voices[i].biquadFilter();

        voices[i].envelope(nBufferFrames, channelCount, sampRate);
        for (int j = 0; j < nBufferFrames * channelCount; j++) { //adds together all the different voices' outputs
            buffer[j] += voices[i].localBuff[j];
        }

    }
    flanger->flanger(buffer);
    chorus->chorus(buffer);
    dly->delay(buffer);
    goodverb->reverb(buffer);
    distortion->distort(buffer);


    return 0;

}

class AudioManager {
public:
    AudioManager() : running(false) {}

    void start() {//Starts the audio on a separate thread so 

        audioThread = std::thread(&AudioManager::audioStart, this);
        audioThread.detach();
    }

    void stop() {
        running = false;
        if (audioThread.joinable()) {
            audioThread.join();
        }
    }

private:
    void audioStart() { //Initializes the audio device.

        RtAudio dac;
        std::vector<unsigned int> deviceIds = dac.getDeviceIds();
        if (deviceIds.size() < 1) {
            wxLogMessage("No audio devices found!");
            return;
        }

        RtAudio::StreamParameters parameters;
        parameters.deviceId = dac.getDefaultOutputDevice(); //Set the device ID to the default output device
        parameters.nChannels = channelCount; //Set the number of channels to 2 (left and right channel for stereo)
        parameters.firstChannel = 0;
        unsigned int sampleRate = sampRate; //Standard CD quality sample rate
        unsigned int bufferFrames = bufferSize; //The number of sample frames. Make this higher for less CPU usage, or lower for less latency. This should be changable by the user in the final version. Also, it should be a power of two.
        double data[2] = { 0, 0 }; //IDK what this does but it was in the example code for the library i downloaded so I'm keeping it for now. I'll remove it if it turns out to be unnecessary.

        if (dac.openStream(&parameters, NULL, RTAUDIO_FLOAT64, sampleRate,
            &bufferFrames, &audioLoop, (void*)&data)) {
            return; //Checks for a problem with device settings
        }

        //Once the stream is opened, this starts the stream
        if (dac.startStream()) {
            return;
        }

        running = true;
        while (running) {
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }

        //Stops the audio stream
        if (dac.isStreamRunning())
            dac.stopStream();

        if (dac.isStreamOpen()) dac.closeStream();

    }

    std::thread audioThread; //Create a new thread to run the audio independent of the GUI
    std::atomic<bool> running; //This value is used to stop the audio thread when the program closes. Since the stop() function is called by the App class destructor, it is declared as an atomic to avoic race conditions. DON'T ADD A UI ELEMENT FOR THIS
};

class KnobControl : public wxPanel {
public:
    KnobControl(wxWindow* parent, wxWindowID id = wxID_ANY, int minValue = 0, int maxValue = 100)
        : wxPanel(parent, id, wxDefaultPosition, wxSize(60, 60), wxBORDER_SIMPLE),
        minValue(minValue), maxValue(maxValue), value((minValue + maxValue) / 2), angle(0) {

        SetBackgroundStyle(wxBG_STYLE_PAINT); //Avoid flickering
        Bind(wxEVT_PAINT, &KnobControl::OnPaint, this);
        Bind(wxEVT_LEFT_DOWN, &KnobControl::OnMouseDown, this);
        Bind(wxEVT_MOTION, &KnobControl::OnMouseMove, this);
        Bind(wxEVT_LEFT_UP, &KnobControl::OnMouseUp, this);
    }

    int GetValue() const { return value; }
    void SetValue(int newValue) {
        if (newValue < minValue) newValue = minValue;
        if (newValue > maxValue) newValue = maxValue;
        value = newValue;
        angle = (value - minValue) * 270.0 / (maxValue - minValue) - 135; //Map value to angle (-135° to 135°)
        Refresh();
    }

private:
    int minValue, maxValue, value, xPrevious, yPrevious;
    double angle = 0;
    bool isDragging = false;


    void OnPaint(wxPaintEvent&) {
        wxAutoBufferedPaintDC dc(this);
        dc.Clear();
        dc.SetBrush(*wxLIGHT_GREY_BRUSH);
        dc.DrawCircle(30, 30, 20); //Draw the knob background

        //Draw indicator line based on angle
        double radians = angle * M_PI / 180.0;
        int x = 30 + 15 * cos(radians);
        int y = 30 - 15 * sin(radians);
        dc.SetPen(wxPen(*wxBLACK, 2));
        dc.DrawLine(30, 30, x, y);
    }

    void OnMouseDown(wxMouseEvent& event) {
        wxPoint pos = event.GetPosition();
        xPrevious = pos.x;
        yPrevious = pos.y;
        isDragging = true;
        CaptureMouse();
    }

    void OnMouseMove(wxMouseEvent& event) {
        if (isDragging) {
            wxPoint pos = event.GetPosition();

            //double newAngle = atan2(30 - pos.y, pos.x - 30) * 180 / M_PI;
            //newAngle = wxClip(newAngle, -135, 135); //Limit rotation
            //angle = newAngle;
            angle += ((pos.y - yPrevious) - (pos.x - xPrevious)); //New equation for the knob angle. When the mouse moves up or to the right, the knob turns clockwise. When it moves down or to the left, the knob turns counter-clockwise.
            xPrevious = pos.x;
            yPrevious = pos.y;
            //Map angle to value
            value = minValue + (angle + 135) * (maxValue - minValue) / 270;
            Refresh();
        }
    }

    void OnMouseUp(wxMouseEvent&) {
        if (isDragging) {
            isDragging = false;
            ReleaseMouse();
        }
    }
};

//****************************************************************************************************************************************************************
//BELOW IS THE GUI CODE
//IT CONTAINS THE ENTRY POINT OF THE PROGRAM
//THE AUDIO AND GUI MUST BE COMPUTED ON SEPARATE THREADS. OTHERWISE THE AUDIO PROCESSING LOOP WILL NOT RUN.
//****************************************************************************************************************************************************************
class App : public wxApp {
public:


    bool OnInit() { //This is the entry point for the program.
        wxFrame* window = new wxFrame(NULL, wxID_ANY, "GUI Test", wxDefaultPosition, wxSize(600, 400));//Creates a window
        wxPanel* panel = new wxPanel(window); //Creates a panel

        KnobControl* volumeKnob = new KnobControl(panel, wxID_ANY, 0, 100);
        volumeKnob->SetValue(50); //Default value


        window->Show();//Shows window
        window->SetFocus();

        window->Bind(wxEVT_KEY_DOWN, &KeyInputManager::OnKeyDown, keyInputManager); //Binds key up event
        window->Bind(wxEVT_KEY_UP, &KeyInputManager::OnKeyUp, keyInputManager); //Binds key down event

        audioManager.start();//Starts the audio in a separate thread

        return true;
    }

    int OnExit() {
        audioManager.stop();
        return 0;
    }

private:

    AudioManager audioManager;
};

wxIMPLEMENT_APP(App); //Initializes the GUI apps