#include <wx/wx.h> //GUI library
#include "RtAudio.h" //Audio library header file
#include <thread> //This lets you create a new thread to run the audio independent of the GUI
#include <atomic>  //Allows you to create atomic variables. Atomic variables are special variables that can be read and written to by multiple threads without causing race conditions.
#include "VoiceFunctions.h" //This header file contains the synth voice class. It will contain the oscillator, envelope, and filter methods that will be used throughout the code.
#include "KeyInputManager.h" //Manages keyboard input
#include "stdc++.h"
#include <stdio.h>
#include <vector>
#include <algorithm>
#include <cmath>
#include <string>
#include <random>
#include "Modulators.h"
#include "fxRack.h"
#include <wx/dcbuffer.h> //Add this include for wxAutoBufferedPaintDC
#include "Goodverb.h"
#include "GUI.h"
#include "GUI2.h"
#include "GUIClasses.h"
#include "GUI3.h"


//****************************************************************************************************************************************************************
//IMPORTANT PART FOR GUI IMPLEMENTATION
//Note: Atomic variables are special variables designed for multithreading. They're designed to prevent race conditions, usually caused by multiple threads/cores
//accessing the same variable at once. Any variables that can be accessed by both the GUI and the audio code should be declared as atomics.
//
//Note #2: It may be necessary to implement something called cache padding so each variable is stored on a separate cache. This is recommended for optimization,
//but I left it out for the sake of simplicity and readability. I may change my mind on this later.
//****************************************************************************************************************************************************************

//GENERAL SYNTH PARAMETERS
//These parameters require reinitialization of the audio device to be changed.
std::atomic<int> sampRate = 44100;//DON'T ADD A UI ELEMENT FOR THIS YET
std::atomic<int> bufferSize = 32;//DON'T ADD A UI ELEMENT FOR THIS YET
std::atomic<bool> reInit = false; //This should trigger the audioStart() method and reinitialize the device. DON'T ADD A UI ELEMENT FOR THIS YET

int voiceCount = 16;//This should be changeable via dropdown menu (NOT YET IMPLEMENTED)
int channelCount = 2;//Not changeable.


voice* voices = new voice[voiceCount];  //Dynamically allocate an array of voice objects.
LFO* LFOs = new LFO[2];
KeyInputManager* keyInputManager = new KeyInputManager(); //Creates keyinput manager object.
Delay* dly = new Delay();
Distortion* distortion = new Distortion();
Flanger* flanger = new Flanger();
Chorus* chorus = new Chorus();
Goodverb* goodverb = new Goodverb();



//Creating global variables
float filtCutoff = 220;
float oscVol = 0.1;





//Creating more global variables for the key tracking purposes


//This loop is called by the audio device once per buffer. It generates audio data in batches and writes it to the buffer.
int audioLoop(void* outputBuffer, void* inputBuffer, unsigned int nBufferFrames,
    double streamTime, RtAudioStreamStatus status, void* userData)
{
    double* buffer = (double*)outputBuffer;
    double* lastValues = (double*)userData;

    if (status)
        wxLogMessage("System Underflow Detected");
    for (int i = 0; i < nBufferFrames; i++) {
        for (int j = 0; j < channelCount; j++) {
            buffer[i * channelCount + j] = 0;
        }
    }

    for (int i = 0; i < 2; i++) {
        LFOs[i].lfoGen();
    }

    keyInputManager->keyScan();

    for (int i = 0; i < voiceCount; i++) {

        voices[i].setVars();

        voices[i].oscillator(nBufferFrames, channelCount); //This is where the oscillator method is called.
        voices[i].oscillator2(nBufferFrames, channelCount);
        //The buffer is filled with the audio data generated by the oscillator. The phase is updated by the oscillator method and returned to the main loop.

        voices[i].biquadCoefs(sampRate); //Sets the coefficients used to calculate the filter output
        voices[i].biquadFilter();

        voices[i].envelope(nBufferFrames, channelCount, sampRate);
        for (int j = 0; j < nBufferFrames * channelCount; j++) { //adds together all the different voices' outputs
            buffer[j] += voices[i].localBuff[j];
        }

    }
    flanger->flanger(buffer);
    chorus->chorus(buffer);
    dly->delay(buffer);
    goodverb->reverb(buffer);
    distortion->distort(buffer);


    return 0;

}

class AudioManager {
public:
    AudioManager() : running(false) {}

    void start() {//Starts the audio on a separate thread so 

        audioThread = std::thread(&AudioManager::audioStart, this);
        audioThread.detach();
    }

    void stop() {
        running = false;
        if (audioThread.joinable()) {
            audioThread.join();
        }
    }

private:
    void audioStart() { //Initializes the audio device.

        RtAudio dac;
        std::vector<unsigned int> deviceIds = dac.getDeviceIds();
        if (deviceIds.size() < 1) {
            wxLogMessage("No audio devices found!");
            return;
        }

        RtAudio::StreamParameters parameters;
        parameters.deviceId = dac.getDefaultOutputDevice(); //Set the device ID to the default output device
        parameters.nChannels = channelCount; //Set the number of channels to 2 (left and right channel for stereo)
        parameters.firstChannel = 0;
        unsigned int sampleRate = sampRate; //Standard CD quality sample rate
        unsigned int bufferFrames = bufferSize; //The number of sample frames. Make this higher for less CPU usage, or lower for less latency. This should be changable by the user in the final version. Also, it should be a power of two.
        double data[2] = { 0, 0 }; //IDK what this does but it was in the example code for the library i downloaded so I'm keeping it for now. I'll remove it if it turns out to be unnecessary.

        if (dac.openStream(&parameters, NULL, RTAUDIO_FLOAT64, sampleRate,
            &bufferFrames, &audioLoop, (void*)&data)) {
            return; //Checks for a problem with device settings
        }

        //Once the stream is opened, this starts the stream
        if (dac.startStream()) {
            return;
        }

        running = true;
        while (running) {
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }

        //Stops the audio stream
        if (dac.isStreamRunning())
            dac.stopStream();

        if (dac.isStreamOpen()) dac.closeStream();

    }

    std::thread audioThread; //Create a new thread to run the audio independent of the GUI
    std::atomic<bool> running; //DON'T ADD A UI ELEMENT FOR THIS. This value is used to stop the audio thread when the program closes. Since the stop() function is called by the App class destructor, it is declared as an atomic to avoic race conditions. DON'T ADD A UI ELEMENT FOR THIS
};




//****************************************************************************************************************************************************************
//BELOW IS THE GUI CODE
//IT CONTAINS THE ENTRY POINT OF THE PROGRAM
//THE AUDIO AND GUI MUST BE COMPUTED ON SEPARATE THREADS. OTHERWISE THE AUDIO PROCESSING LOOP WILL NOT RUN.
//****************************************************************************************************************************************************************

 //std::atomic<double> cutoffSet = 220.0;

class App : public wxApp {
public:


    bool OnInit() {
        // Create the main window and panel.
        wxFrame* window = new wxFrame(NULL, wxID_ANY, "Synthesizer", wxDefaultPosition, wxSize(800, 600), wxDEFAULT_FRAME_STYLE | wxWANTS_CHARS);
        wxPanel* panel = new wxPanel(window);
        panel->SetCanFocus(false);//Makes it so the panel can't steal focus from the window
        window->SetCanFocus(true);
        // -------------------------------------------------
        // Main Vertical Sizer for the entire panel.
        // -------------------------------------------------
        wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);

        // -------------------------------------------------
        // TOP ROW: EG Box in Upper Right Corner (2x2 grid).
        // -------------------------------------------------
        wxBoxSizer* topSizer = new wxBoxSizer(wxHORIZONTAL);
        topSizer->AddStretchSpacer(1); // Push EG box to the right.

        /***************************************************
        * GUI Functions are called below
        ****************************************************/
        quanGUI(window, panel);
        GUI2(window, panel, mainSizer);

        // -------------------------------------------------
        // LOWER ROW: Keyboard Visualization and Debugging Box.
        // -------------------------------------------------
        wxBoxSizer* lowerSizer = new wxBoxSizer(wxHORIZONTAL);

        PianoKeyboard* pianoKeyboard = new PianoKeyboard(panel, wxID_ANY);
        pianoKeyboard->SetMinSize(wxSize(600, 100));

        // Increase the debug box size to 200x300 so all text is visible (no scrolling needed).
        wxTextCtrl* debugBox = new wxTextCtrl(panel, wxID_ANY, "",
            wxDefaultPosition, wxSize(200, 300),
            wxTE_MULTILINE | wxTE_READONLY | wxBORDER_SIMPLE);

        lowerSizer->AddStretchSpacer(1);
        lowerSizer->Add(pianoKeyboard, 0, wxALL, 10);
        lowerSizer->Add(debugBox, 0, wxALL | wxALIGN_RIGHT, 10);
        lowerSizer->AddStretchSpacer(1);
        mainSizer->Add(lowerSizer, 0, wxEXPAND | wxALL, 10);

        panel->SetSizer(mainSizer);
        window->Show();
        window->SetFocus();

        // -------------------------------------------------
        // Key Event Bindings: Update our KeyInputManager and refresh the PianoKeyboard.
        // -------------------------------------------------
        //window->Bind(wxEVT_KEY_DOWN, [=](wxKeyEvent& event) {//Key down event
        //    char key = static_cast<char>(event.GetUnicodeKey());
        //    key = toupper(key);
        //    if (key >= 'A' && key <= 'P') {
        //        // Refresh immediately so the key color updates.
        //        pianoKeyboard->Refresh();
        //    }
        //    keyInputManager->OnKeyDown(event);
        //    event.Skip();
        //    });

        //window->Bind(wxEVT_KEY_UP, [=](wxKeyEvent& event) {//Key up event
        //    char key = static_cast<char>(event.GetUnicodeKey());
        //    key = toupper(key);
        //    if (key >= 'A' && key <= 'P') {
        //        pianoKeyboard->Refresh();
        //    }
        //    keyInputManager->OnKeyUp(event);
        //    event.Skip();
        //    });



        // -------------------------------------------------
        // Timer: Update the Debugging Box with EG values and Keyboard States.
        // -------------------------------------------------
        wxTimer* updateTimer = new wxTimer(window);
        window->Bind(wxEVT_TIMER, [=](wxTimerEvent&) {
            //int attackVal = attackKnob->GetValue();
            //int decayVal = decayKnob->GetValue();
            //int sustainVal = sustainKnob->GetValue();
            //int releaseVal = releaseKnob->GetValue();

            wxString debugText;
            //debugText << "Envelope Generator:\n";
            //debugText << "Attack: " << attackVal << "\n";
            //debugText << "Decay: " << decayVal << "\n";
            //debugText << "Sustain: " << sustainVal << "\n";
            //debugText << "Release: " << releaseVal << "\n\n";
            //debugText << "Keyboard States:\n";

            //Note: noteSet has (usually) 16 entries, one for each voice object. The voice objects are designed to be set to any note, and the input logic in keyinputmanager is designed to dynamically set the frequency of each voice to match the notes being held down.
            //The reason why I don't have one voice for each note is because it would take a ton of CPU power for that. This method of allocating voices is standard for pretty much all digital synths.
            size_t numKeys = keyInputManager->noteSet.size();
            for (size_t i = 0; i < numKeys && i < 16; i++) {
                char keyLabel = 'A' + i;
                char noteValue = keyInputManager->noteSet[i];
                wxString state;
                if (noteValue != ' ')
                    state.Printf("%c (pressed)", noteValue);
                else
                    state = "off";
                debugText << keyLabel << ": " << state << "\n";
            }
            debugBox->SetValue(debugText);
            });
        updateTimer->Start(50); // Update every 50 ms.

        // -------------------------------------------------
        // Start Audio Processing.
        // -------------------------------------------------
        audioManager.start();

        return true;
    }


    int OnExit() noexcept {
        audioManager.stop();
        return 0;
    }

private:

    AudioManager audioManager;
};

wxIMPLEMENT_APP(App); //Initializes the GUI apps